# Value types
const RDA_TYPE_INTEGER = 1
const RDA_TYPE_FLOAT = 2
const RDA_TYPE_STRING = 3
const RDA_TYPE_DATE = 4
const RDA_TYPE_DATETIME = 5
const RDA_TYPE_TIME = 6
const RDA_TYPE_CATEGORY = 7

# Transformation types
const RDA_TRANSFORMATION_TYPE_INGEST = 1
const RDA_TRANSFORMATION_TYPE_TRANSFORM = 2

# Transformation statuses
const RDA_TRANSFORMATION_STATUS_UNVERIFIED = 1
const RDA_TRANSFORMATION_STATUS_VERIFIED = 2